return {
  { -- Highlight, edit, and navigate code
    'nvim-treesitter/nvim-treesitter',
    branch = 'main',
    lazy = false,
    build = ':TSUpdate',
    opts = {
      ensure_installed = {
        'astro',
        'bash',
        'css',
        'gitcommit',
        'go',
        'graphql',
        'html',
        'javascript',
        'json',
        'json5',
        'lua',
        'markdown',
        'nix',
        'php',
        'prisma',
        'python',
        'regex',
        'sql',
        'svelte',
        'typescript',
        'terraform',
        'vim',
        'vue',
      },
      -- Autoinstall languages that are not installed
      auto_install = true,
      highlight = {
        enable = true,
      },
      indent = { enable = true },
    },
  },
}
