{ lib, ... }: {
  # Generated by nixos-infect from the active Hetzner VPS.
  # If the server is recreated, pull this again from /etc/nixos/networking.nix
  networking = {
    nameservers = [ "8.8.8.8" ];
    defaultGateway = "172.31.1.1";
    defaultGateway6 = {
      address = "fe80::1";
      interface = "eth0";
    };
    dhcpcd.enable = false;
    usePredictableInterfaceNames = lib.mkForce false;
    interfaces = {
      eth0 = {
        ipv4.addresses = [
          { address = "46.225.79.92"; prefixLength = 32; }
        ];
        ipv6.addresses = [
          { address = "2a01:4f8:1c19:fa80::1"; prefixLength = 64; }
          { address = "fe80::9000:7ff:fe57:2eea"; prefixLength = 64; }
        ];
        ipv4.routes = [ { address = "172.31.1.1"; prefixLength = 32; } ];
        ipv6.routes = [ { address = "fe80::1"; prefixLength = 128; } ];
      };
    };
  };
  services.udev.extraRules = ''
    ATTR{address}=="92:00:07:57:2e:ea", NAME="eth0"
  '';
}
