{
  inputs,
  pkgs,
  ...
}:
let
  hermesAgent = inputs.hermes-agent.packages.${pkgs.stdenv.hostPlatform.system}.messaging;
in
{
  environment.systemPackages = with pkgs; [
    vim
    alt-tab-macos
    chatgpt
    colima
    docker
    docker-buildx
    docker-compose
    home-manager
    hidden-bar
    postman
    raycast
    signal-desktop
    ytmdesktop
    google-chrome
    gh
    jankyborders
    hermesAgent
  ];
}
