{
  pkgs,
  ...
}:
{
  home.packages = with pkgs; [
    zip
    xz
    unzip
    p7zip
    signal-desktop
    plex-desktop
    ferdium
    mangohud
    protonup-ng
    ytmdesktop
    libnotify
    pavucontrol
    blueman
    hyprshot
    swappy
    cliphist
    hyprpaper
    obsidian
    orca-slicer
    vlc
    samrewritten
    bun
    bruno
    kubectl
    alvr
    intiface-central
    winboat
    (google-chrome.override {
      commandLineArgs = [
        "--remote-debugging-port=9222"
        "--remote-debugging-address=127.0.0.1"
        "--user-data-dir=$HOME/.config/google-chrome-debug"
      ];
    })
    qalculate-qt
    vesktop
  ];
}
